<?php
$products = [
    'chicco-pram' => [
        'id' => 'chicco-pram',
        'brand' => 'Chicco',
        'name' => 'Compact Baby Pram',
        'price' => 4500,
        'image' => 'assets/images/gallery/products/recommended/chicco-pram.png',
        'condition' => 'Like New',
        'seller' => 'Sarah M.',
        'seller_rating' => 4.9,
        'seller_reviews' => 4,
        'seller_avatar' => 'assets/images/gallery/sellers/sarah-m.jpg',
        'location' => 'Sandton, Johannesburg',
        'age' => '0-6 months',
        'categories' => ['Prams & Strollers', 'Travel & Sleep'],
        'listing_id' => 'PLB-584726',
        'url' => 'product-detail.php?id=chicco-pram',
        'short_desc' => 'Chicco compact pram, used for four months. Folds flat, canopy and harness in good nick. Rain cover and cup holder included.',
        'description' => 'Chicco compact pram, used for four months. Folds flat, canopy and harness in good nick. Rain cover and cup holder included.',
        'details' => [
            'Condition: Like new',
            'Used for: 4 months',
            'Suitable for: Newborns to 6 months',
            'Smoke-free, pet-free home',
        ],
    ],
    'breast-pump' => [
        'id' => 'breast-pump',
        'brand' => 'Medela',
        'name' => 'Electric Breast Pump',
        'price' => 2800,
        'image' => 'assets/images/gallery/products/recommended/breast-pump.png',
        'condition' => 'Like New',
        'seller' => 'Lerato N.',
        'seller_rating' => 4.8,
        'seller_reviews' => 8,
        'seller_avatar' => 'assets/images/gallery/sellers/lerato-n.jpg',
        'location' => 'Sea Point, Cape Town',
        'age' => 'N/A',
        'categories' => ['Breast Pumps', 'Feeding'],
        'listing_id' => 'PLB-591204',
        'url' => 'product-detail.php?id=breast-pump',
        'short_desc' => 'Medela electric pump, used for three months with my second. All parts there, cleaned and packed in the original bag.',
        'description' => 'Medela electric pump, used for three months with my second. All parts there, cleaned and packed in the original bag.',
        'details' => [
            'Condition: Like new',
            'Used for: 3 months',
            'Includes flanges, bottles and carry bag',
            'Smoke-free home',
        ],
    ],
    'baby-cot' => [
        'id' => 'baby-cot',
        'brand' => 'Stokke',
        'name' => 'Wooden Baby Cot',
        'price' => 3200,
        'image' => 'assets/images/gallery/products/recommended/baby-cot.png',
        'condition' => 'Good',
        'seller' => 'Priya K.',
        'seller_rating' => 5.0,
        'seller_reviews' => 6,
        'seller_avatar' => 'assets/images/gallery/sellers/priya-s.jpg',
        'location' => 'Umhlanga, Durban',
        'age' => '0-3 years',
        'categories' => ['Nursery Furniture', 'Sleep'],
        'listing_id' => 'PLB-578901',
        'url' => 'product-detail.php?id=baby-cot',
        'short_desc' => 'Stokke wooden cot. Both kids slept in it. One scuff on the side rail, shown in photos. Mattress included.',
        'description' => 'Stokke wooden cot. Both kids slept in it. One scuff on the side rail, shown in photos. Mattress included.',
        'details' => [
            'Condition: Good',
            'Used for: 2 years',
            'Mattress included',
            'Pet-free home',
        ],
    ],
    'car-seat' => [
        'id' => 'car-seat',
        'brand' => 'Nuna',
        'name' => 'Group 0+ Car Seat',
        'price' => 3500,
        'image' => 'assets/images/gallery/products/recommended/car-seat.jpg',
        'condition' => 'Like New',
        'seller' => 'Thabo M.',
        'seller_rating' => 4.7,
        'seller_reviews' => 9,
        'seller_avatar' => 'assets/images/gallery/sellers/thabo-m.jpg',
        'location' => 'Centurion, Pretoria',
        'age' => 'Birth to 13 kg',
        'categories' => ['Car Seats', 'Travel'],
        'listing_id' => 'PLB-602118',
        'url' => 'product-detail.php?id=car-seat',
        'short_desc' => 'Nuna Group 0+ seat, never been in an accident. Isofix base and rain cover included.',
        'description' => 'Nuna Group 0+ seat, never been in an accident. Isofix base and rain cover included.',
        'details' => [
            'Condition: Like new',
            'Used for: 8 months',
            'Isofix base included',
            'Smoke-free car',
        ],
    ],
    'high-chair' => [
        'id' => 'high-chair',
        'brand' => 'Chicco',
        'name' => 'Convertible High Chair',
        'price' => 1800,
        'image' => 'assets/images/gallery/products/recommended/high-chair.png',
        'condition' => 'Good',
        'seller' => 'Chris W.',
        'seller_rating' => 4.9,
        'seller_reviews' => 5,
        'seller_avatar' => 'assets/images/gallery/sellers/chris-w.jpg',
        'location' => 'Rosebank, Johannesburg',
        'age' => '6 months+',
        'categories' => ['High Chairs', 'Feeding'],
        'listing_id' => 'PLB-595447',
        'url' => 'product-detail.php?id=high-chair',
        'short_desc' => 'Chicco high chair that converts to a booster. Tray comes off for cleaning. Straps a bit faded but everything works.',
        'description' => 'Chicco high chair that converts to a booster. Tray comes off for cleaning. Straps a bit faded but everything works.',
        'details' => [
            'Condition: Good',
            'Used for: 18 months',
            'Converts to booster seat',
            'Smoke-free home',
        ],
    ],
    'bugaboo-fox' => [
        'id' => 'bugaboo-fox',
        'brand' => 'Bugaboo',
        'name' => 'Bugaboo Fox 5 Stroller',
        'price' => 12500,
        'image' => 'assets/images/gallery/product-images/01.png',
        'condition' => 'Good',
        'seller' => 'Kate W.',
        'seller_rating' => 4.8,
        'seller_reviews' => 3,
        'seller_avatar' => 'assets/images/gallery/sellers/kate-w.jpg',
        'location' => 'Gardens, Cape Town',
        'age' => '0-4 years',
        'categories' => ['Prams & Strollers', 'Travel & Sleep'],
        'listing_id' => 'PLB-610882',
        'url' => 'product-detail.php?id=bugaboo-fox',
        'short_desc' => 'Bugaboo Fox 5 with bassinet. One child, kept indoors. Bassinet, rain cover and cup holder included.',
        'description' => 'Bugaboo Fox 5 with bassinet. One child, kept indoors. Bassinet, rain cover and cup holder included.',
        'details' => [
            'Condition: Good',
            'Used for: 8 months',
            'Bassinet and rain cover included',
            'Smoke-free, pet-free home',
        ],
    ],
];
